language: java
sudo: false

matrix:
  include:
    - env: JDK='OpenJDK 8'
      jdk: openjdk8
    - env: JDK='OracleJDK 8'
      jdk: oraclejdk8
    - env: JDK='OpenJDK 9'
      install: . ./install-jdk.sh -F 9 -L GPL
    - env: JDK='OracleJDK 9'
      jdk: oraclejdk9
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
    - env: JDK='OracleJDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
    - env: JDK='OracleJDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL

before_install: wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

after_success:
  - if [[ "${JDK}" == 'OpenJDK 8' ]]; then
      mvn deploy --settings .travis-settings.xml -DskipTests=true -B || travis_terminate 1;
    fi
