language: java
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

after_success:
  - if [[ "${TRAVIS_JDK_VERSION}" == 'openjdk8' ]]; then
      mvn deploy --settings .travis-settings.xml -DskipTests=true -B || travis_terminate 1;
    fi
